---
title: "Mean Daily Plaza Traffic"
output: html_document
---

#### Reporting the current status of the subway trains.

    Data format is as follows for each element:
      {
        "count": 26774.09756097561,
        "id": 1,
        "name": "Robert F. Kennedy Bridge Bronx Plaza"
      },
  
For this example, we will apply the same pattern for laying out our chart elements as the preceding list. Instead of using list items to build up our visualization, here we are using div tags with specified widths to draw the rectangles that make up the bar chart.

Each div in the body will represent one data entry (place i.e. "row of data") and will contain 2 sub divs, one for the actual bar and value, and another for the label indicating the place that the data corresponds to.
```{}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <script type="text/javascript" src="d3.js"></script>
  <style>
    
    //CSS to add style to the plot
    
    div.chart{
      font-family:sans-serif;
      font-size:0.7em;
    }
  
    div.bar {
      background-color:DarkRed;
      color:white;
      height:3em;
      line-height:3em;
      padding-right:1em;
      margin-bottom:2px;
      text-align:right;
      margin-left:22em;
    }
  
    div.label {
      height:3em;
      line-height:3em;
      padding-right:1em;
      margin-bottom:2px;
      float:left;
      width:20em;
      text-align:right;
    }
  
  </style>

  <script>
  
  function draw(data) {
    "use strict";
    
    d3.select("body")
      .append("div")
      
      //Here the containing element is a div tag, whose class is set to “chart.” 
      //This allows us to select it later, and apply any styles that are appropriate for the whole chart.
      
      .attr("class","chart") 
        
      //We then select all the div tags whose class is bar—as before this is an empty selection.
      .selectAll("div.bar") 
      
      //We join the empty selection to our data.
      .data(data.cash)
      
      //Then generate the entering selection—an array with one element per data point.
      .enter()
      
      //We append div tags...
      .append("div") 
      
      //With class "line".
      .attr("class","line") 
      
      //Add name label
      d3.selectAll("div.line")
      .append("div")
      .attr("class","label")
      .text(function(d){return d.name})
      
      //Add bar
      d3.selectAll("div.line")
      .append("div")
      .attr("class","bar")
      .style("width", function(d){return d.count/100 + "px"})
      .text(function(d){return Math.round(d.count)});
  }
  
  </script>
</head>
<body>
  <script>
  d3.json("data/plaza_traffic.json", draw);
  </script>
</body>
</html>
```

#### The output takes the following form:
<br></br>

<style>
    
    div.chart{
      font-family:sans-serif;
      font-size:0.7em;
      margin: auto;
      width: 500px
      height: 500px
    }
  
    div.bar {
      background-color:DarkRed;
      color:white;
      height:3em;
      line-height:3em;
      padding-right:1em;
      margin-bottom:2px;
      text-align:right;
      margin-left:22em;
    }
  
   div.label {
    height:3em;
    line-height:3em;
    padding-right:1em;
    margin-bottom:2px;
    float:left;
    width:20em;
    text-align:right;
    }
  
</style>
<script src="http://d3js.org/d3.v3.min.js" charset="utf-8"></script>
<script src="https://google-code-prettify.googlecode.com/svn/loader/run_prettify.js"></script>
<script>

function draw(data) {
    "use strict";
    
    d3.select("body")
      .append("div")
      .attr("class","chart")
      .selectAll("div.bar")
      .data(data.cash)
      .enter()
      .append("div")
      .attr("class","line")
      
      d3.selectAll("div.line")
      .append("div")
      .attr("class","label")
      .text(function(d){return d.name})
      
      d3.selectAll("div.line")
      .append("div")
      .attr("class","bar")
      .style("width", function(d){return d.count/100 + "px"})
      .text(function(d){return Math.round(d.count)});
  }
</script>
</head>
<body>
  <script>
    d3.json("data/plaza_traffic.json", draw);
  </script>
</body>
</html>